name: Jest Tests
on:
  push:
    paths:
      - './src/**/*.spec.js'

jobs:
  build:
    name: Jest Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - run: npm test